// <auto-generated />
namespace GOGO.RMS.ESV.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class POCOAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(POCOAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202204181937445_POCOAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
